### ISSUE TITLE
Bad last updated value for Boosted after having renamed the default branch

### ISSUE THREAD

**Issue by julien-deramond** [Orange-OpenSource/Orange-OpenSource.github.io#6]
The card for Boosted displays that the project was updated for the last time 1 month ago, but yet it was [updated yesterday](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap) at the time I'm writing this:

![Capture d’écran 2021-10-08 à 09 10 03](https://user-images.githubusercontent.com/17381666/136513570-2f2d0f33-1bbc-4a2a-a686-4498b85144cf.png)

This is an extract of the API result:
```json
{
  [...]
  "default_branch": "v5-dev",
  "updated_at": "2021-09-06T15:54:22Z",
  [...]
}
```

Indeed we renamed with the GitHub tool the default branch the 9th of September via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/792 from `v5-dev` to `main`.

Do you know if we missed something while renaming the default branch?

**Comment by bbailleux** [comment]
The list of repositories is read once in a while (I do not have the delay in mind, but it is a few hours, and less than 24 hours for sure) and kept in a file that the page reads each time it loads.

Thus it is possible that the content was not up to date at the time you have looked at it.

I have had a look at the page and the "_Updated … ago_" is currently accurate.

I close the issue, but feel free to open it again if needed.

Regards.

**Comment by bbailleux** [comment]
Closed due to not repro
